name: 'Bump version and tag/release'
on:
  push:
    branches:
      - 'develop'
permissions: write-all
jobs:
  bump-version:
    name: 'Bump version and tag/release'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v2'
        with:
          ref: ${{ github.ref }}
      - name: 'cat package.json'
        run: cat ./package.json
      - name: 'Automated version bump'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        with:
          tag-prefix: 'v'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'cat package.json'
        run: cat ./package.json
      - name: 'Output step'
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"
      - uses: ncipollo/release-action@v1
        name: 'Create release from recently created tag'
        with:
          tag: ${{ steps.version-bump.outputs.newTag }}
